In [1]:
import numpy as np
import pandas as pd
X=np.array([[0, 0, 0],[0, 0, 1],[0, 1, 0],[0, 1, 1],[1, 0, 0],[1, 0, 1],[1, 1, 0],[1, 1, 1]])

In [2]:
#<--------------different input functions as truth table----------------------------->
y1=np.array([[0],[0],[0],[0],[1],[1],[1],[1]])
y2=np.array([[0],[1],[0],[1],[1],[0],[1],[1]])
y3=np.array([[1],[1],[0],[0],[1],[0],[1],[1]])
y4=np.array([[0],[1],[1],[0],[1],[0],[0],[1]])
y5=np.array([[0],[1],[0],[1],[0],[1],[0],[1]])
functions=np.array([y1,y2,y3,y4,y5])


In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigder(x):
    return sigmoid(x)*(1-sigmoid(x))

In [4]:
def my_neural(X,y):
    epochs=1500
    learn_rate=0.9
    w1=np.random.rand(3,10)
    w2=np.random.rand(10,1)
    b1=0
    b2=0
    for i in range(epochs):
        h1=sigmoid(np.dot(X,w1)+b1)
        y_pred=sigmoid(np.dot(h1,w2)+b2)
        dw2=np.dot(h1.T,2*(y_pred-y)*y_pred*(1-y_pred))
        dw1=np.dot(X.T,np.dot(2*(y_pred-y)*y_pred*(1-y_pred),w2.T)*h1*(1-h1))
        w2-=learn_rate*dw2
        w1-=learn_rate*dw1
        if(i%100==0):
            h1=sigmoid(np.dot(X,w1))
            y_pred=sigmoid(np.dot(h1,w2))
            print ("Traning Loss after epoch "+str(i)+"\n"+str (np.mean(np.square(y - y_pred))))
    return y_pred

## 1) for first function

In [5]:
ypred=my_neural(X,y1)
print("-------------------------------------------")
print("Predicted output after :\n",ypred)
print("Real output :\n",y1)

Traning Loss after epoch 0
0.4281337233661932
Traning Loss after epoch 100
0.0016753584688785584
Traning Loss after epoch 200
0.0006492773408416486
Traning Loss after epoch 300
0.0003914188983063626
Traning Loss after epoch 400
0.0002771322608419022
Traning Loss after epoch 500
0.0002133053281208785
Traning Loss after epoch 600
0.00017279380295711
Traning Loss after epoch 700
0.00014489302188282606
Traning Loss after epoch 800
0.00012455552233481867
Traning Loss after epoch 900
0.00010909897765206232
Traning Loss after epoch 1000
9.696971731139495e-05
Traning Loss after epoch 1100
8.720720085274923e-05
Traning Loss after epoch 1200
7.918643010376346e-05
Traning Loss after epoch 1300
7.248362135287901e-05
Traning Loss after epoch 1400
6.680149970688848e-05
-------------------------------------------
Predicted output after :
 [[0.01414552]
 [0.00565865]
 [0.00559778]
 [0.00273155]
 [0.99218802]
 [0.99283831]
 [0.99272459]
 [0.99225605]]
Real output :
 [[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 

## for second function

In [6]:
ypred=my_neural(X,y2)
print("-------------------------------------------")
print("Predicted output after :\n",ypred)
print("Real output :\n",y2)

Traning Loss after epoch 0
0.3256371996544555
Traning Loss after epoch 100
0.10770807041604587
Traning Loss after epoch 200
0.043127692450495775
Traning Loss after epoch 300
0.010548520721721669
Traning Loss after epoch 400
0.004006968236644973
Traning Loss after epoch 500
0.002261824662577073
Traning Loss after epoch 600
0.0015263613591049502
Traning Loss after epoch 700
0.0011342262147635885
Traning Loss after epoch 800
0.0008945009822538522
Traning Loss after epoch 900
0.0007343426338316426
Traning Loss after epoch 1000
0.0006204872891881188
Traning Loss after epoch 1100
0.0005357557826869108
Traning Loss after epoch 1200
0.0004704440175914937
Traning Loss after epoch 1300
0.0004186833054751621
Traning Loss after epoch 1400
0.0003767286644728592
-------------------------------------------
Predicted output after :
 [[0.00454538]
 [0.9758469 ]
 [0.00884919]
 [0.99893698]
 [0.97241508]
 [0.03450809]
 [0.9962044 ]
 [0.99040166]]
Real output :
 [[0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]


## for third function

In [7]:
ypred=my_neural(X,y3)
print("-------------------------------------------")
print("Predicted output after :\n",ypred)
print("Real output :\n",y3)

Traning Loss after epoch 0
0.2924826755129828
Traning Loss after epoch 100
0.12789710103146998
Traning Loss after epoch 200
0.1258650347790574
Traning Loss after epoch 300
0.12548108676146996
Traning Loss after epoch 400
0.12532715242127127
Traning Loss after epoch 500
0.12524567164518624
Traning Loss after epoch 600
0.12519568872570075
Traning Loss after epoch 700
0.12516207737795562
Traning Loss after epoch 800
0.12513800984029633
Traning Loss after epoch 900
0.12511997053788773
Traning Loss after epoch 1000
0.12510597173208066
Traning Loss after epoch 1100
0.1250948078502448
Traning Loss after epoch 1200
0.12508570664013602
Traning Loss after epoch 1300
0.12507815127014307
Traning Loss after epoch 1400
0.12507178319890172
-------------------------------------------
Predicted output after :
 [[0.98775245]
 [0.99226299]
 [0.01066436]
 [0.01198487]
 [0.99999665]
 [0.99999301]
 [0.99289076]
 [0.9947279 ]]
Real output :
 [[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]


## for fourth function

In [8]:
ypred=my_neural(X,y4)
print("-------------------------------------------")
print("Predicted output after :\n",ypred)
print("Real output :\n",y4)

Traning Loss after epoch 0
0.4464557924404719
Traning Loss after epoch 100
0.24995304088772274
Traning Loss after epoch 200
0.2496248971140987
Traning Loss after epoch 300
0.24354844322529554
Traning Loss after epoch 400
0.06102658563726524
Traning Loss after epoch 500
0.010485137569974622
Traning Loss after epoch 600
0.004634528899011295
Traning Loss after epoch 700
0.002730088946273477
Traning Loss after epoch 800
0.0018527537938590275
Traning Loss after epoch 900
0.00136911371481539
Traning Loss after epoch 1000
0.0010705107325824819
Traning Loss after epoch 1100
0.0008710696809415107
Traning Loss after epoch 1200
0.0007299513293266116
Traning Loss after epoch 1300
0.0006256114082819056
Traning Loss after epoch 1400
0.0005457540350066184
-------------------------------------------
Predicted output after :
 [[0.03577978]
 [0.97372707]
 [0.97845389]
 [0.01250938]
 [0.9720938 ]
 [0.01761604]
 [0.01366148]
 [0.99767522]]
Real output :
 [[0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]


## for fifth function

In [9]:
ypred=my_neural(X,y5)
print("-------------------------------------------")
print("Predicted output after :\n",ypred)
print("Real output :\n",y5)

Traning Loss after epoch 0
0.46992639049629475
Traning Loss after epoch 100
0.0013964376282825197
Traning Loss after epoch 200
0.0005845021629309574
Traning Loss after epoch 300
0.0003616589851625418
Traning Loss after epoch 400
0.00025960899877424564
Traning Loss after epoch 500
0.000201578656387291
Traning Loss after epoch 600
0.00016431114494593784
Traning Loss after epoch 700
0.00013842815520015357
Traning Loss after epoch 800
0.00011944079369098451
Traning Loss after epoch 900
0.00010493727627986456
Traning Loss after epoch 1000
9.350878425904025e-05
Traning Loss after epoch 1100
8.427842016757843e-05
Traning Loss after epoch 1200
7.667242470220686e-05
Traning Loss after epoch 1300
7.029993016173988e-05
Traning Loss after epoch 1400
6.488564934244834e-05
-------------------------------------------
Predicted output after :
 [[0.01405887]
 [0.99318044]
 [0.00576967]
 [0.99314463]
 [0.00588095]
 [0.99287411]
 [0.00275896]
 [0.99193054]]
Real output :
 [[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [